---
title: "GEO77 2022"
author: "Nicolás Riveras Muñoz"
date: "`r format(Sys.time(), '%d %B, %Y, %H:%M')`"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "docs", output_file =  "index.html", knit_root_dir = rprojroot::find_rstudio_root_file()) })
output: 
    html_document:
      toc: false
      toc_depth: 3
      toc_float: false
      number_sections: true
      self_contained: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction to exploratory data analysis

```{r, echo=FALSE}
library(downloadthis)
## Link in Github repo
download_link(
  link = "https://nriveras.github.io/GEO77_2022/EDA.html",
  button_label = "Web version",
  button_type = "default",
  has_icon = FALSE,
  self_contained = TRUE
)
```

```{r, echo=FALSE}
## Link in Github repo
download_link(
  link = "https://github.com/nriveras/GEO77_2022/blob/main/data/soil_data.txt?raw=true",
  button_label = "dataset",
  button_type = "default",
  has_icon = TRUE,
  icon = "fa fa-save",
  self_contained = TRUE
)
```
# Introduction spatial modeling

```{r, echo=FALSE}
## Link in Github repo
download_link(
  link = "https://nriveras.github.io/GEO77_2022/geostats.html",
  button_label = "Web version",
  button_type = "default",
  has_icon = FALSE,
  self_contained = TRUE
)
```
```{r, echo=FALSE}
## Link in Github repo
download_link(
  link = "https://github.com/nriveras/GEO77_2022/blob/main/GEO77_Info_WS2223_ENG.pdf?raw=true",
  button_label = "dataset",
  button_type = "default",
  has_icon = TRUE,
  icon = "fa fa-save",
  self_contained = TRUE
)
